### ISSUE TITLE
Failed to send requesterrorApi returned invalid status: 404 Not Found

### ISSUE THREAD

**Issue by denisgolius** [grafana/kubernetes-app#60]
```
root@grafana:~# grafana-cli plugins install kubernetes-app
Failed to send requesterrorApi returned invalid status: 404 Not Found
Error: ✗ Failed to send request. error: Api returned invalid status: 404 Not Found

NAME:
   Grafana cli plugins install - install <plugin id> <plugin version (optional)>

USAGE:
   Grafana cli plugins install [arguments...]
```

**Comment by dennisameling** [comment]
Looks like your command has a typo:

`grafana-cli plugins install kubernetes-app`

should be

`grafana-cli plugins install grafana-kubernetes-app`

Hope this helps :)

**Comment by denisgolius** [comment]
> Looks like your command has a typo:
> 
> `grafana-cli plugins install kubernetes-app`
> 
> should be
> 
> `grafana-cli plugins install grafana-kubernetes-app`
> 
> Hope this helps :)

Ok, so why there is another way to install on Grafana portal?  
https://grafana.com/plugins/grafana-kubernetes-app
![screenshot 17](https://user-images.githubusercontent.com/5650611/52550219-c2c29600-2ddf-11e9-81cf-9ecbab38daab.png)

**Comment by dennisameling** [comment]
@denisgolius Looks like a small error in the docs to me. If you look at the "Installation" tab on this page: https://grafana.com/plugins/grafana-kubernetes-app/installation, it shows you the `grafana-kubernetes-app` instead of `kubernetes-app`.

I guess the package authors should correct the typo in the Grafana plugins directory then.
